language: node_js
node_js: '7.0'

install:
  - npm install -g bower grunt-cli jshint karma
  - npm install
  - bower install

cache:
  directories:
    - node_modules
    - bower_components

script: grunt karma
